### ISSUE TITLE
code not working

### ISSUE THREAD

**Issue by jungjin09** [handsomezebra/ffsearch#2]
This function not found in ffsearch.h
void UpdateTextCandidate(std::string const& key, size_t start, size_t end, size_t idx, size_t pos);

Also iteration variable for what?
you should explain the context of the variables?

**Comment by hzeng-otterai** [comment]
Oh, right, thanks for pointing out. The UpdateTextCandidate function is not needed any more. I will remove that.

I don't quite understand your question about iteration variable. Could you help to clarify?

**Comment by hzeng-otterai** [comment]
UpdateTextCandidate is removed from the header. Please reopen the issue if you have more questions.
